###
POST http://localhost:5000/register HTTP/1.1
content-type: application/json

{
    "name": "Cristian",
    "telephone": "+380956507248",
    "email": "test@gmail.com",
    "password": "123123"
}


###
POST http://localhost:5000/login HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "123123"
}



###
POST http://localhost:5000/alert HTTP/1.1
content-type: application/json

